### ISSUE TITLE
This fork seems incomplete

### ISSUE THREAD

**Issue by vraravam** [pacstah/ferdium#6]
I used to be a core contributor (maintainer) of ferdi - please see other thread for background.

I have the source code for the desktop app and the recipes. But, when i diff with this forked repo - I see many files missing and some of the build-outputs included. Please cleanup, or move to my fork: https://github.com/vraravam/ferdi

**Comment by dqos** [comment]
Hello @vraravam! Nice to see a core contributor. We are working on reviving the project, would you mind helping us out?
A lot of people of the community are on our Discord: https://discord.gg/xpNTzgKmHM

**Comment by vraravam** [comment]
Thanks @dqos - I tried that url for discord - but, it keeps rejecting me.

**Comment by vraravam** [comment]
Either way, if you can either blast away this fork and into mine (or vice versa) - Im fine. My only request is to recreate as much of the **original history** as possible (I had the main repo updated till a few days ago), but the `recipes` is a month or so old. I dont' think there was any significant code merged in the past month or more though

**Comment by dqos** [comment]
@vraravam we are already working with a lot of people restoring the history, so would really appreciate your help. Can you try the Discord link? Or Telegram or Email?

Thanks!

**Comment by vraravam** [comment]
hi - I have pinged you on telegram TMR12

**Comment by vraravam** [comment]
Closing this ticket since all is sorted, and now I understand why this repo is the way it is.
